### ISSUE TITLE
Testing the app on device

### ISSUE THREAD

**Issue by chrisrogers3d** [pillarpond/imagesegmenter#2]
Seems to run and show the camera image, does not seem to do anything else.
Looking at the demo, it should segment people and bicycles?
Issue #1 is closed but there have not been any checkins since then.
Does that mean I need to figure out how to disable the GPU delegate myself?

**Comment by pillarpond** [comment]
Please test it with commit https://github.com/pillarpond/image-segmenter-android/commit/36e1dd245dca25c8f44e9e217ca280a3a1bf9f1c
