### ISSUE TITLE
Help with test on device

### ISSUE THREAD

**Issue by Azazel17** [pillarpond/imagesegmenter#3]
Sir, the app compiles but does nothing, any help would be appreciatted

**Comment by pillarpond** [comment]
Please test it with commit https://github.com/pillarpond/image-segmenter-android/commit/36e1dd245dca25c8f44e9e217ca280a3a1bf9f1c

**Comment by Azazel17** [comment]
> Please test it with commit [36e1dd2](https://github.com/pillarpond/image-segmenter-android/commit/36e1dd245dca25c8f44e9e217ca280a3a1bf9f1c)

Thank you sr. works great. You have the label color map please? 

Question:

On my galaxy S10+ works very fast but the segmentation map is not so accurate. How can i improve the segmentation map? 

By the way can i capture at "less" frames per second? 

Finally can i retrain my model and how quantize the model ?

Thanks in advance

**Comment by pillarpond** [comment]
You have the label color map please?
=> Please refer to the code below.
https://github.com/pillarpond/image-segmenter-android/blob/36e1dd245dca25c8f44e9e217ca280a3a1bf9f1c/app/src/main/java/pp/imagesegmenter/Deeplab.java#L94

How can i improve the segmentation map?
=> You can resize input tensor size.
```java
interpreter.resizeInput(0, new int[]{1, height, width, 3});
```
By the way can i capture at "less" frames per second?
=> Add your condition in here.
https://github.com/pillarpond/image-segmenter-android/blob/36e1dd245dca25c8f44e9e217ca280a3a1bf9f1c/app/src/main/java/pp/imagesegmenter/MainActivity.java#L189

Finally can i retrain my model and how quantize the model ?
=> Please refer to [the link](https://github.com/tensorflow/models/blob/1498d9419b799c3df61d8a8b63a879dcbca4504e/research/deeplab/g3doc/quantize.md#converting-to-tflite-flatbuffer).
