### ISSUE TITLE
Question : Can you color the object detected on the camera live?

### ISSUE THREAD

**Issue by raghunandankavi2010** [pillarpond/imagesegmenter#5]
Is it possible to change the color of bitmap dynamically and render the same on live camera.

I just want to know how to do it. If you have any possible ideas or solutions for the same. we have a similar requirement which can help us.

**Comment by pillarpond** [comment]
It's impossible now.
But I think that you can change colormap dynamically.
Please refer to [the link](https://github.com/pillarpond/image-segmenter-android/blob/36e1dd245dca25c8f44e9e217ca280a3a1bf9f1c/app/src/main/java/pp/imagesegmenter/Deeplab.java#L94).
