### ISSUE TITLE
How to trian my model and replace the old tflite?

### ISSUE THREAD

**Issue by RobinHan24** [pillarpond/imagesegmenter#7]
Hi,sir, could you please tell me how to train my own model and export the tflite, thank you very much.

**Comment by pillarpond** [comment]
Please refer to [the link](https://github.com/tensorflow/models/blob/1498d9419b799c3df61d8a8b63a879dcbca4504e/research/deeplab/g3doc/quantize.md#converting-to-tflite-flatbuffer).
